<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bibilioteca.Domain\Bibilioteca.Domain.csproj" />
    <ProjectReference Include="..\Biblioteca.Application\Biblioteca.Application.csproj" />
  </ItemGroup>

</Project>
